#' Read ED2 variables
#'
#' @param path path to the h5 files folder generated by ED2
#' @param sites site(s) or prefix(es)
#' @param type Q, T, D, etc.
#' @param variables variables to read in, as defined by the names in the h5 files
#' @param include_units include units description?
#' @param verbose (optional) echo's some progress on screen
#'
#' @return list of the form ed$site$var
#' @export
readVar.ED2 <- function(path,sites,type,vars="all",yearlim="all",include_units=TRUE,verbose=FALSE){

  suppressMessages(require(lubridate))
  suppressMessages(require(rhdf5))
  suppressMessages(require(abind))

  ##
  ## PREPARATION
  ##

  # List all output files within the selected limits
  files.edout <- list.files(path = path, pattern = paste0("-",type,"-"))
  if(length(files.edout)==0) stop("No files of type ",type," found in ",path)

  # Time management tools
  sec_per_day <- 24*60*60
  yrdays <- function(tim){ return(365 + leap_year(tim)) }

  ##
  ## READ DATA
  ##

  if(verbose) cat("readOut.ED2 :: Reading data. ")

  # Initialize list
  ed <- list()
  for(s in sites) ed[[s]] <- list()

  # Read
  for(s in sites){

    # Length of the prefix
    ind <- nchar(s)

    files.site <- files.edout[startsWith(files.edout,s)]
    if(length(files.site)<1) stop("No data found for site ",s)

    # Check if the year of the file is in the requested interval. Remove if not.
    files.site.keep <- logical()
    for(f in 1:length(files.site)){
      fileyear <- substr(files.site[[f]],ind+4,ind+7)
      files.site.keep[f] <- (yearlim[1]=="all" | (fileyear>=min(yearlim) & fileyear<=max(yearlim)))
    }
    files.site <- files.site[files.site.keep]


    for(f in 1:length(files.site)){

      # Save date info from filename
      ed[[s]]$year[f]  <- substr(files.site[f],ind+4,ind+7)
      ed[[s]]$month[f] <- substr(files.site[f],ind+9,ind+10)
      ed[[s]]$day[f]   <- substr(files.site[f],ind+12,ind+13)

      # Get variables in this file
      h5vars <- h5ls(file.path(path,files.site[f]));
      if(vars[1]=="all") vars <- h5vars$name

      # Read all vars of interest
      for(v in vars){
        if(v %in% h5vars$name){
          ed[[s]][[v]][[f]] <- h5read(file.path(path,files.site[f]),name=v);
        } else {
          stop(v," not found in file ",files.site[f],call. = FALSE)
        }

      }
      H5close()

    }

  }


  if(verbose) cat("Done!\n")

  ##
  ## CONVERT DATES ETC.
  ##

  if(verbose) cat("readOut.ED2 :: Rearranging dates and vars a bit. ")

  # POSIX and variable arrangement fix
  for(s in sites) {


    #
    ## Q OUT
    #
    if(type=="Q"){
      ed[[s]]$posix <- with_tz(as.POSIXct(with_tz(ymd(paste0(ed[[s]]$year,ed[[s]]$month,"01")))),tzone="UTC")
      ed[[s]]$year  <- NULL
      ed[[s]]$month <- NULL
      ed[[s]]$day   <- NULL
      hour(ed[[s]]$posix)<-0
      minute(ed[[s]]$posix)<-0
      second(ed[[s]]$posix)<-0
    }


    #
    ## DAILY OUT
    #
    if(type=="D"){
      ed[[s]]$posix <- with_tz(as.POSIXct(with_tz(ymd(paste0(ed[[s]]$year,ed[[s]]$month,ed[[s]]$day)))),tzone="UTC")
      ed[[s]]$year  <- NULL
      ed[[s]]$month <- NULL
      ed[[s]]$day   <- NULL
      hour(ed[[s]]$posix)<-0
      minute(ed[[s]]$posix)<-0
      second(ed[[s]]$posix)<-0
    }

    #
    ## TOWER OUT
    #
    if(type=="T"){
      yrs <- length(ed[[s]]$year)

      # Generate sequence of POSIX each half hour
      yr.fr <- min(as.numeric(ed[[s]]$year))
      yr.to <- max(as.numeric(ed[[s]]$year))
      pos.fr <- as.POSIXct(ymd(paste0(yr.fr,"0101"),tz="UTC"))
      pos.to <- as.POSIXct(ymd(paste0(yr.to+1,"0101"),tz="UTC"))-minutes(30)
      ed[[s]]$posix <- seq.POSIXt(from=pos.fr,to=pos.to,by="30 min")
      ed[[s]]$year  <- NULL
      ed[[s]]$month <- NULL
      ed[[s]]$day   <- NULL

    }

    # Concatenate all vars
    for(v in vars){
      lastdim <- length(dim(ed[[s]][[v]][[1]])) # WATCH OUT: here we assume that the "last" dimension is the time dimension (ipoly), which is the case for T files
      ed[[s]][[v]] <- drop(do.call(abind,list(ed[[s]][[v]],along=lastdim)))
    }
  }

  if(verbose) cat("Done!\n")

  ##
  ## FINISHING TOUCH
  ##

  for(s in sites){
    for(v in names(ed[[s]])){
      attr(ed[[s]][[v]],"dimnames")   <- NULL
    }

    if(include_units){
      for(v in vars){
        attr(ed[[s]][[v]],"Units")      <- varInfo.ED2[[v]]$Units
      }
    }
  }

  return(ed)

}
